import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="relative w-full py-6 bg-[#09090B] shadow-md z-10">
          <nav className="container mx-auto flex justify-between items-center px-4">
            <Link href="/" className="text-xl font-bold text-gray-100">
              Mockiew
            </Link>
            <div>
              <Button className="mr-4" variant="ghost">
                Giriş Yap
              </Button>
              <Button className="text-white">Kayıt Ol</Button>
            </div>
          </nav>
        </header>
        {children}
        <footer className="relative w-full py-6 bg-[#09090B] text-white text-center z-10">
          <p>&copy; 2024 Mockiew. Tüm hakları saklıdır.</p>
        </footer>
      </body>
    </html>
  );
}
